[5. PATCH api/review/review_id] allows you to increment the votes sco…
Proto-Will/backend-games pull request #5
Opened 2022-07-05 11:24 UTC by Proto-Will

…re by whatever number is input

2022-07-05 11:47 UTC, emilyb93 commented on __tests__/api.test.js
> +    })
Id like to see some error handling here!

What happens if we try to vote for non existent articles/ wrong data type for the id?
What about if the patch request body we send is malformed/missing keys/wrong data etc?

2022-07-05 11:49 UTC, emilyb93 requested changes
Would like to see more consideration for error handling please

2022-07-05 11:49 UTC, emilyb93 commented on __tests__/api.test.js
>              })
Id like to see some error handling for this endpoint. What if we request an out of range review? What if we request a review with an id that isnt a number?

2022-07-06 08:55 UTC, CatHoang reviewed
Hi Will, good extra error handling tests, however I would also suggest looking at testing for wrong data type for the value if it is not a number?

2022-07-06 10:11 UTC, CatHoang approved these changes
Looks great Will, feel free to merge!

2022-07-06 10:11 UTC, merged